# Pull Request Checks for Solarium Web Portal
name: PR Checks

on:
  pull_request:
    branches: [main, develop]

jobs:
  # Basic validation
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check environment configuration
        run: ./scripts/env-check.sh

      - name: Type checking
        run: npm run typecheck

      - name: Linting
        run: npm run lint

      - name: Format checking
        run: npm run format:check

      - name: Run tests
        run: npm run test:ci

      - name: Build check
        run: npm run build:development

      - name: Bundle size check
        run: |
          npm run build:production
          BUNDLE_SIZE=$(du -sh dist | cut -f1)
          echo "Bundle size: $BUNDLE_SIZE"

          # Check if bundle is too large (>5MB)
          BUNDLE_SIZE_MB=$(du -sm dist | cut -f1)
          if [ $BUNDLE_SIZE_MB -gt 5 ]; then
            echo "::warning::Bundle size ($BUNDLE_SIZE) is larger than 5MB"
          fi

  # Comment on PR with build info
  pr-comment:
    name: PR Comment
    runs-on: ubuntu-latest
    needs: validate
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and analyze
        run: |
          npm run build:production
          BUNDLE_SIZE=$(du -sh dist | cut -f1)
          JS_FILES=$(find dist -name "*.js" | wc -l)
          CSS_FILES=$(find dist -name "*.css" | wc -l)

          echo "BUNDLE_SIZE=$BUNDLE_SIZE" >> $GITHUB_ENV
          echo "JS_FILES=$JS_FILES" >> $GITHUB_ENV
          echo "CSS_FILES=$CSS_FILES" >> $GITHUB_ENV

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const { BUNDLE_SIZE, JS_FILES, CSS_FILES } = process.env;
            const comment = `
            ## 🚀 Build Results

            **Bundle Analysis:**
            - **Size:** ${BUNDLE_SIZE}
            - **JavaScript files:** ${JS_FILES}
            - **CSS files:** ${CSS_FILES}

            **Environment Check:** ✅ Passed
            **Type Check:** ✅ Passed
            **Linting:** ✅ Passed
            **Tests:** ✅ Passed
            **Build:** ✅ Passed

            Ready for review! 🎉
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
